In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
#numpy1
import numpy as np
a=np.array([2,1,3])
b=np.array([5,3,9])
print("Array1:")
print(a)
print("Array2:")
print(b)
print("Multiplication of two arrays a and b:")
print(np.multiply(a,b))

Array1:
[2 1 3]
Array2:
[5 3 9]
Multiplication of two arrays a and b:
[10  3 27]


In [4]:
#numpy2
import numpy as np
a=np.array([[2,np.nan,8],
            [np.nan,5,7]])
print("given array:")
print(a)
print("\nmissing array:")
print(np.isnan(a))

given array:
[[ 2. nan  8.]
 [nan  5.  7.]]

missing array:
[[False  True False]
 [ True False False]]


In [5]:
#numpy3
import numpy as np
a=np.array([2,4,5,6])
print("Array1:",a)
b=np.array([4,6])
print("Array2:",b)
print(np.in1d(a,b))

Array1: [2 4 5 6]
Array2: [4 6]
[False  True False  True]


In [6]:
#numpy4
import numpy as np
a=np.array([[1,2,4],
            [6,7,3]])
np.savetxt('myarray.txt',a)

In [8]:
#numpy5
import numpy as np
a=np.linspace(2.5,6.5,30)
print(a)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [9]:
#pandas1
import pandas as pd
a=pd.Series([
    ['Dhoni','Virat','Sachin'],
    ['Faf','Shakib']
])
print("Given array:")
print(a)
a=a.apply(pd.Series).stack().reset_index(drop=True)
print(a)

Given array:
0    [Dhoni, Virat, Sachin]
1             [Faf, Shakib]
dtype: object
0     Dhoni
1     Virat
2    Sachin
3       Faf
4    Shakib
dtype: object


In [2]:
#pandas2
import pandas as pd
import pandas as pd
a=pd.Series([0,1,2,3,4,5,6,7,8])
print("Given series:",a)
print("\nSubset series:")
n=4
b=a[a<n]
print(b)

Given series: 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

Subset series:
0    0
1    1
2    2
3    3
dtype: int64


In [20]:
#pandas3
import pandas as pd
import numpy as np
a = pd.Series(np.random.randint(1, 5, [15]))
print("Given Series:")
print(a)
print("Freq:", a.value_counts())
r = a[~a.isin(a.value_counts().index[:1])] = 'Other'
print(a)

Given Series:
0     4
1     1
2     3
3     4
4     1
5     1
6     3
7     4
8     3
9     2
10    4
11    2
12    1
13    3
14    3
dtype: int32
Freq: 3    5
4    4
1    4
2    2
Name: count, dtype: int64
0     Other
1     Other
2         3
3     Other
4     Other
5     Other
6         3
7     Other
8         3
9     Other
10    Other
11    Other
12    Other
13        3
14        3
dtype: object


In [23]:
#pandas4
import pandas as pd 
import numpy as np 
a= pd.Series(np.random.randint(1, 25, 15)) 
print("Given Series:\n") 
print(a)
r = np.argwhere(a % 5==0) 
print("Positions of numbers that are multiples of 5:\n") 
print(r)

Given Series:

0     14
1     21
2      3
3      1
4     23
5     10
6     14
7      2
8     17
9      4
10     9
11    23
12    12
13    12
14    20
dtype: int32
Positions of numbers that are multiples of 5:

[[ 5]
 [14]]


In [24]:
#pandas5
import pandas as pd
a= pd.Series(['Dhoni', 'Virat', 'Sachin', 'Faf'])
print("Given Series:")
print(a)
r=a.map(lambda x: len(x))
print("\nNumber of characters:")
print(r)

Given Series:
0     Dhoni
1     Virat
2    Sachin
3       Faf
dtype: object

Number of characters:
0    5
1    5
2    6
3    3
dtype: int64


In [39]:
#pandas6
import pandas as pd
from dateutil.parser import parse
a = pd.Series(['Mar 2004', 'Nov 2003', 'Nov 2005', 'Feb 2011', 'Mar 2015'])
print("Given Series:")
print(a)
print("\nNew dates:")
r=a.map(lambda d: parse('9' + d))
print(r)

Given Series:
0    Mar 2004
1    Nov 2003
2    Nov 2005
3    Feb 2011
4    Mar 2015
dtype: object

New dates:
0   2004-03-09
1   2003-11-09
2   2005-11-09
3   2011-02-09
4   2015-03-09
dtype: datetime64[ns]


In [29]:
#pandas7
import pandas as pd
import numpy as np
a= {'name': ['Prash', 'Megh', 'Nick', 'Sunny', 'Bhav', 'Nav'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20],
        'attempts': [1, 3, 2, 3, 2, 3],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes']}
labels= ['a', 'b', 'c', 'd', 'e', 'f']
c= pd.DataFrame(a , index=labels)
print(c)

    name  score  attempts qualify
a  Prash   12.5         1     yes
b   Megh    9.0         3      no
c   Nick   16.5         2     yes
d  Sunny    NaN         3      no
e   Bhav    9.0         2      no
f    Nav   20.0         3     yes


In [30]:
#pandas8
import pandas as pd
import numpy as np
a= {'name': ['Prash', 'Megh', 'Nick', 'Sunny', 'Bhav', 'Nav'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20],
        'attempts': [1, 3, 2, 3, 2, 3],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes']}
labels= ['a', 'b', 'c', 'd', 'e', 'f']
b= pd.DataFrame(a , index=labels)
print("Number of attempts in the examination is greater than 2:")
print(b[b['attempts'] > 2])

Number of attempts in the examination is greater than 2:
    name  score  attempts qualify
b   Megh    9.0         3      no
d  Sunny    NaN         3      no
f    Nav   20.0         3     yes


In [34]:
#pandas9
import pandas as pd
import numpy as np
a= {'name': ['Prash', 'Megh', 'Nick', 'Sunny', 'Bhav', 'Nav'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20],
        'attempts': [1, 3, 2, 3, 2, 3],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes']}
labels= ['a', 'b', 'c', 'd', 'e', 'f']
b= pd.DataFrame(a , index=labels)
print("Given rows:")
print(b)
print("\nAppend a new row:")
b.loc['a'] = ['Prash',1,12.5, 'yes']
print("Print all records after insert a new record:")
print(b)
print("\nDelete the new row and display the original  rows:")
b=b.drop('a')
print(b)


Given rows:
    name  score  attempts qualify
a  Prash   12.5         1     yes
b   Megh    9.0         3      no
c   Nick   16.5         2     yes
d  Sunny    NaN         3      no
e   Bhav    9.0         2      no
f    Nav   20.0         3     yes

Append a new row:
Print all records after insert a new record:
    name  score  attempts qualify
a  Prash    1.0      12.5     yes
b   Megh    9.0       3.0      no
c   Nick   16.5       2.0     yes
d  Sunny    NaN       3.0      no
e   Bhav    9.0       2.0      no
f    Nav   20.0       3.0     yes

Delete the new row and display the original  rows:
    name  score  attempts qualify
b   Megh    9.0       3.0      no
c   Nick   16.5       2.0     yes
d  Sunny    NaN       3.0      no
e   Bhav    9.0       2.0      no
f    Nav   20.0       3.0     yes


In [35]:
#pandas10
import pandas as pd
import numpy as np
a= {'name': ['Prash', 'Megh', 'Nick', 'Sunny', 'Bhav', 'Nav'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20],
        'attempts': [1, 3, 2, 3, 2, 3],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes']}
labels= ['a', 'b', 'c', 'd', 'e', 'f']
b= pd.DataFrame(a , index=labels)
print("Given rows:")
print(b)
b=b.sort_values(by=['name', 'score'], ascending=[False, True])
print("Sort the data frame:")
print(b)


Given rows:
    name  score  attempts qualify
a  Prash   12.5         1     yes
b   Megh    9.0         3      no
c   Nick   16.5         2     yes
d  Sunny    NaN         3      no
e   Bhav    9.0         2      no
f    Nav   20.0         3     yes
Sort the data frame:
    name  score  attempts qualify
d  Sunny    NaN         3      no
a  Prash   12.5         1     yes
c   Nick   16.5         2     yes
f    Nav   20.0         3     yes
b   Megh    9.0         3      no
e   Bhav    9.0         2      no


In [36]:
#pandas11
import pandas as pd
import numpy as np
a={'name': ['Prash', 'Megh', 'Nick', 'Sunny', 'Bhav', 'Nav'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20],
        'attempts': [1, 3, 2, 3, 2, 3],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes']}
labels= ['a', 'b', 'c', 'd', 'e', 'f']
b= pd.DataFrame(a , index=labels)
print("Given rows:")
print(b)
print("\nReplace the 'qualify' column contains the values 'yes' and 'no'  with True and  False:")
b['qualify'] = b['qualify'].map({'yes': True, 'no': False})
print(b)


Given rows:
    name  score  attempts qualify
a  Prash   12.5         1     yes
b   Megh    9.0         3      no
c   Nick   16.5         2     yes
d  Sunny    NaN         3      no
e   Bhav    9.0         2      no
f    Nav   20.0         3     yes

Replace the 'qualify' column contains the values 'yes' and 'no'  with True and  False:
    name  score  attempts  qualify
a  Prash   12.5         1     True
b   Megh    9.0         3    False
c   Nick   16.5         2     True
d  Sunny    NaN         3    False
e   Bhav    9.0         2    False
f    Nav   20.0         3     True


In [37]:
#pandas12
import pandas as pd
import numpy as np
b= pd.DataFrame([1000, 2000, 3000, -4000, np.inf, -np.inf])
print("Given DataFrame:")
print(b)
print("Removing infinite values:")
b=b.replace([np.inf, -np.inf], np.nan)
print(b)

Given DataFrame:
        0
0  1000.0
1  2000.0
2  3000.0
3 -4000.0
4     inf
5    -inf
Removing infinite values:
        0
0  1000.0
1  2000.0
2  3000.0
3 -4000.0
4     NaN
5     NaN
